import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import {
  ButtonPrimary,
  ButtonSecondary,
  ButtonTertier,
} from "../components/Button/Button";
import { CardsHome } from "../components/CardsHome/CardsHome";
import { EventCards } from "../components/EventsCards/EventCards";
import { Header } from "../components/Header/Header";
import styles from "../styles/Home.module.css";
import moment from "moment";
import { useMutation } from "@apollo/client";
import { ADD_EVENT } from "../graphql/Mutation";
import { Footer } from "../components/Footer/Footer";

const Home: NextPage = () => {
  const [title, setTitle] = useState("");
  const [desc, setDesc] = useState("");
  const [image, setImage] = useState("");
  const [location, setLocation] = useState("");
  const [date, setDate] = useState("");
  const [quota, setQuota] = useState(0);

  const handleChangeTitle = (e: any) => {
    const value = e.target.value;
    setTitle(value);
  };
  const handleChangeDesc = (e: any) => {
    const value = e.target.value;
    setDesc(value);
  };
  const handleChangeImage = (e: any) => {
    const value = e.target.value;
    setImage(value);
  };
  const handleChangeLocation = (e: any) => {
    const value = e.target.value;
    setLocation(value);
  };
  const handleChangeDate = (e: any) => {
    const date = e.target.value;
    const newDate = new Date(date);
    const newsDate = moment(newDate).format();
    setDate(newsDate);
    console.log(newsDate);
  };
  const handleChangeQuota = (e: any) => {
    const value = e.target.value;
    setQuota(value);
  };

  const [inputEvent, { loading, error, data }] = useMutation(ADD_EVENT);

  const handleAddEvent = () => {
    inputEvent({
      variables: {
        title: title,
        image: image,
        description: desc,
        location: location,
        date: date,
        quota: quota,
      },
      onCompleted: (data) => {
        console.log(data);
      },
      context: {
        headers: {
          Authorization:
            "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVkIjoxNjQzOTk2MTg4LCJpZCI6Mn0.f1xe367BDQONzlWlCSouqYkr4nQYxrdXDCkq5d7xBfw",
        },
      },
    });
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <div
        style={{
          marginTop: "10px",
          padding: "0px 100px",
        }}>
        {/* <CardsHome />
        <CardsHome />
        <CardsHome />
        <CardsHome /> */}
        <EventCards />
      </div>
      <div className='p-3 w-50 d-flex flex-column mb-5'>
        <label htmlFor=''>title</label>
        <input type='text' onChange={handleChangeTitle} />
        <label htmlFor=''>Image</label>
        <input type='text' onChange={handleChangeImage} />
        <label htmlFor=''>Desc</label>
        <input type='text' onChange={handleChangeDesc} />
        <label htmlFor=''>Location</label>
        <input type='text' onChange={handleChangeLocation} />
        <label htmlFor=''>Date</label>
        <input type='datetime-local' onChange={handleChangeDate} />
        <label htmlFor=''>Quota</label>
        <input type='number' onChange={handleChangeQuota} />
        <button onClick={handleAddEvent}>Add Event</button>
      </div>
      {/* <InputText /> */}
      <Footer />
    </div>
  );
};

export default Home;
